### ISSUE TITLE
Add logging capabilities

### ISSUE THREAD

**Issue by mihirnimgade** [UBC-Solar/sunlink#5]
`link_telemetry.py` should log the raw messages it receives from the radio module along with the parsed measurements it extracted from the raw messages. It would be enough to log these inside simple text files. The idea behind extensive logging is that it allows us to perform postmortem analysis on what raw data we received and how the script dealt with it. This is an essential debugging tool.

Using the `logging` module provided in the Python standard library would be a good idea since it provides support for log levels (e.g., debug, info, warning, error, critical) and a bunch of other customization.

The log levels for each of these is up to the implementer.

We can split up the implementation into stages:

## Stage 1

- [ ] Replace all the `print` and `pp.pprint` statements in `link_telemetry.py` with calls to one of `logging.critical()`, `logging.error()`, `logging.warning()`, `logging.info()`, or `logging.debug()`. Here you would need to decide how important each piece of logged information is.
- [ ] Customize the `logging` instance so the log is in a useful format. The most important thing is that it contains a timestamp.

## Stage 2

- [ ] During `link_telemetry.py` execution, write the current logging output to a single text file in a new folder called `logs`.
- [ ] Add the `logs` folder to the project's `.gitignore` file.
- [ ] Come up with a useful naming convention for the text file.

## Stage 3

- [ ] Ensure the Python script writes to a different text file every time it is executed.
- [ ] Add a custom command line parameter (`--log`) that enables/disables logging.

## Stage 4

- [ ] At the beginning of execution, log what mode `link_telemetry` is in (NORMAL or DEBUG)
- [ ] Log the messages being sent to Grafana
- [ ] Log the messages being sent to InfluxDB
